import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPlus } from '@fortawesome/free-solid-svg-icons'

import { api } from "@/utils/api";

import DidgYaListItem from "@/components/DidgYaListItem";
import "@/modules/arrayExtensions"

export default function Home() {
  const user = useUser();
  let data = [];

  if (user.isLoaded) {
    console.log("userId:", user?.user.id)
    const result = api.didgya.getAllByUserId.useQuery({ userId: user?.user.id });
    data = result?.data || [];
  }

  function createDidgYa(userId: string) {
    if (!userId) return console.log("Please log in to create a DidgYa.");
    console.log(`Creating a new DidgYa as ${userId}...`);
  }

  return (
    <>
      <Head>
        <title>DidgYa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            <span className="text-primary-light dark:text-primary-dark">Didg</span><span className="text-supporting-light dark:text-supporting-dark">Ya</span>
          </h1>
          <div className="tracking-tight max-w-lg text-center text-xl">
            Did you do it? Did you experience it? 
            <span className="font-bold mx-1.5">
            <span className="text-primary-light dark:text-primary-dark">Didg</span><span className="text-supporting-light dark:text-supporting-dark">Ya</span>
            </span>
            is an app designed to simplify the way you track various things that happen in your life.
          </div>
          <div className="bg-primary-light dark:bg-primary-dark text-text-dark dark:text-text-dark rounded-lg shadow-2xl px-4 py-2 font-bold text-2xl hover:bg-primary-light/60 hover:dark:bg-primary-dark/60 cursor-pointer">
            {!user.isSignedIn && <SignInButton/>}
            {!!user.isSignedIn && <SignOutButton/>}
          </div>
          <div className="flex flex-col items-center justify-start w-full h-fit gap-1">
            <div 
              className="flex flex-row gap-4 pl-3 pr-1.5 py-1.5 bg-supporting-light dark:bg-supporting-dark items-center justify-between text-3xl flex-no-wrap max-w-md w-full text-white hover:bg-supporting-light/80 hover:dark:bg-supporting-dark/80 cursor-pointer rounded-full" 
              key={"create-didgya"}
              onClick={()=>createDidgYa(user.user.id)}
            >
              <div className="text-2xl cursor-pointer rounded-md p-1 grow-0 shrink opacity-0">🤷</div>
              <div className="text-xl text-left grow shrink-0">Create DidgYa</div>
              <div className="flex flex-row gap-2 items-center"></div>
              <span id="play-button" className="mr-3 w-6 text-highlight-light dark:text-highlight-dark cursor-pointer">
                  <FontAwesomeIcon icon={faPlus} />
              </span>
            </div>
            {data?.map((didgya) => (
              <DidgYaListItem 
                key={didgya.id}
                {...didgya} 
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
