import Head from "next/head";
import { SignInButton } from "@clerk/nextjs";

import { api } from "@/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>DidgYa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Didg<span className="text-[hsl(280,100%,70%)]">Ya</span>
          </h1>
          <div className="max-w-lg text-center text-xl tracking-tight text-white">
            Did you do it? Did you experience it? Didg
            <span className="text-[hsl(280,100%,70%)]">Ya</span> is an app
            designed to simplify the way you track various things that happen in
            your life.
          </div>
          <div className="rounded-lg bg-white px-4 py-2 text-2xl font-bold text-black shadow-2xl">
            <SignInButton />
          </div>
        </div>
      </main>
    </>
  );
}
